n = input('Dígite qualquer coisa, número, letra ou número e letra: ')
print('O tipo primitivo desse valor é: ', type(n))
print('esse valor é todo numerico: {}'.format(n.isnumeric()))
print('esse valor é alphabetico: {}'.format(n.isalpha()))
print('esse valor é decimal: {}'.format(n.isdecimal()))
print('esse valor está entre os sistema ASCII: {}'.format(n.isascii()))
print('esse valor são todos letras maiusculas: {}'.format(n.isupper()))
print('esse valor tem espaço: {}'.format(n.isspace()))
print('esse valor é um digito: {}'.format(n.isdigit()))
print('esse valor pode ser usado: {}'.format(n.isidentifier()))
print('esse valor é imprimivel: {}'.format(n.isprintable()))
print('esse valor é capitalizado: {}'.format(n.istitle()))
